extends RefCounted

# Authored visual lengths in map cells, GENERATED by tools/build_overhead_atlas.py
# (alpha-span of each drawing in assets/travel/vehicles-overhead.json divided
# by the locomotive's, rounded to 0.01; test_travel_world.gd checks they match
# the manifest). Drawn proportions, not historical masses or capacity rules.
# Codex's 25 masters are all drawn about the same length (0.99-1.01), XL types
# included: the art does not show the XL wagons as longer, so neither does this.
const LENGTHS := {"locomotive": 1.0, "general-quarters": 1.01, "boudoir": 0.99, "observatory": 0.99, "prison": 1.0, "alcatraz": 1.0, "livestock": 1.0, "drill": 1.0, "harpoon": 1.0, "observation-box": 1.0, "cannon": 1.0, "machine-gun": 1.0, "missile-launcher": 1.0, "tank": 1.0, "oil": 0.99, "crane": 1.0, "merchandise": 0.99, "xl-merchandise": 0.99, "bio-greenhouse": 1.0, "refrigerator": 1.0, "tender": 1.01, "spy": 1.0, "barracks": 0.99, "xl-barracks": 1.0, "boiler": 0.99}

# Wagon type (train_wagons.gd TYPE, reference-private/commerce.json
# "wagon_names" 1-25) -> drawing, GENERATED by tools/build_overhead_atlas.py
# from the catalogue's type_id. One remake drawing per original type
# (output/imagegen/wagon-redesign-20260926 catalogue, owner choice 2026-09-26); the
# silhouettes are remake art, not reconstructed original sprites. Types 17
# and 23 keep the accepted prototype's dome and turret despite the historical
# names MERCHANDISE and BARRACKS (catalogue README).
const TYPE_TO_KIND := {1: "locomotive", 2: "general-quarters", 3: "boudoir", 4: "observatory", 5: "prison", 6: "alcatraz", 7: "livestock", 8: "drill", 9: "harpoon", 10: "observation-box", 11: "cannon", 12: "machine-gun", 13: "missile-launcher", 14: "tank", 15: "oil", 16: "crane", 17: "merchandise", 18: "xl-merchandise", 19: "bio-greenhouse", 20: "refrigerator", 21: "tender", 22: "spy", 23: "barracks", 24: "xl-barracks", 25: "boiler"}

var vehicles: Array[String] = ["locomotive", "tender", "general-quarters", "boudoir", "merchandise", "barracks"]


# Precondition: wagon_table exposes `wagons` (Array of [type, state, goods,
# quantity], train_wagons.gd's TYPE index) and is never null.
# Postcondition: vehicles holds one entry per wagon whose type is in
# TYPE_TO_KIND, same relative order as wagon_table.wagons; a type outside
# 1-25 contributes nothing (not a placeholder, not a fabricated generic
# sprite). Composition is therefore always a pure function of
# wagon_table; there is no independent state to fall out of sync with it.
func derive_from_wagons(wagon_table) -> void:
	var derived: Array[String] = []
	for wagon in wagon_table.wagons:
		var kind: Variant = TYPE_TO_KIND.get(wagon[wagon_table.TYPE])
		if kind != null:
			derived.append(kind)
	vehicles = derived


func snapshot() -> Array:
	return vehicles.duplicate()


func length_world() -> float:
	var total := 0.0
	for kind in vehicles:
		total += LENGTHS[kind]
	return total
